import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync, writeFileSync, symlinkSync} from 'node:fs';
import {join} from 'node:path';
import {fixture, message, encryptedMessage, NONCE, ROOT_DID, TARGET_DID} from './helpers/probe-fixture.mjs';
import {runProbe, formatProbe} from '../oats-package/capabilities/oats-aweb/lib/probe.mjs';
import {proofMessage, fullNonce} from '../oats-package/capabilities/oats-aweb/lib/probe-proof.mjs';
import {ProbeError, parseProbeArgs, parseProbeJson, ProbeBudget, runProbeChild} from '../oats-package/capabilities/oats-aweb/lib/probe-runtime.mjs';
const claims = {from: TARGET_DID, to: ROOT_DID, conversation: 'conversation-1', nonce: NONCE, distinctFrom: 'request-1'};
const sends = f => f.calls.filter(c => c.args.includes('send'));
for (const encrypted of [false, true]) test(`${encrypted ? 'decrypted v2' : 'signed plaintext'} exact reply PASS`, async t => {
  const f = fixture(t, {reply: encrypted ? encryptedMessage() : message()});
  const r = await runProbe(f.args, f.deps);
  assert.equal(r.outcome, 'PASS', r.reason); assert.equal(sends(f).length, 1);
  assert.equal(r.reply.messageId, 'reply-1'); assert(r.timing.replyMs >= 0); assert.equal(r.target.delivery, 'broker');
  assert.equal(r.diagnostics.versions.harness.status, 'unknown'); assert.equal(r.diagnostics.pane.state, 'unknown');
  assert.equal(JSON.parse(formatProbe(r, true)).outcome, 'PASS'); assert.match(formatProbe(r, false), /^PASS /);
  for (const c of f.calls) assert.equal(existsSync(c.options.cwd), false);
  assert(!JSON.stringify(r).includes(NONCE)); assert(!JSON.stringify(r).includes('secret'));
});
for (const [name, change] of Object.entries({did: m => m.from_did = ROOT_DID, recipient: m => m.to_did = TARGET_DID, thread: m => m.conversation_id = 'wrong', nonce: m => m.body = 'absent', id: m => m.message_id = 'request-1', verified: m => m.verification_status = 'verified_legacy', stale: m => m.verification_status = 'verification_stale', boolean: m => m.verification_status = true, unsignedDisplayBody: m => m.body += ' changed', unsignedId: m => m.message_id = 'unsigned-id', type: m => m.type = 'chat', payloadType: m => {const p = JSON.parse(m.signed_payload);p.type = 'chat';m.signed_payload = JSON.stringify(p);}, payloadAbsent: m => delete m.signed_payload, payloadArray: m => m.signed_payload = '[]', payloadDuplicate: m => m.signed_payload = '{"type":"mail","type":"mail"}', payloadOversized: m => m.signed_payload = ' '.repeat(1024 * 1024 + 1)})) test(`plaintext rejects ${name}`, () => { const m = message(); change(m); assert.equal(proofMessage(m, claims), false); });
for (const [name, change] of Object.entries({mode: m => m.content_mode = 'legacy_plaintext_v1', version: m => m.message_version = 1, envelope: m => delete m.encrypted_envelope, type: m => m.encrypted_envelope.kind = 'chat', id: m => m.encrypted_envelope.message_id = 'wrong', thread: m => m.encrypted_envelope.conversation_id = 'wrong', sender: m => m.encrypted_envelope.from.did = ROOT_DID, recipient: m => m.encrypted_envelope.recipients[0].did = TARGET_DID, recipients: m => m.encrypted_envelope.recipients = [], failed: m => m.verification_status = 'failed', nonce: m => m.body = 'absent'})) test(`encrypted v2 rejects ${name}`, () => {const m = encryptedMessage(); change(m); assert.equal(proofMessage(m, claims), false);});
test('nonce is a whole token, not a substring', () => {assert(fullNonce(`(${NONCE})`, NONCE)); for (const body of [`a${NONCE}`, `${NONCE}_`, `${NONCE}-x`]) assert(!fullNonce(body, NONCE));});
for (const args of [[], ['--home', 'relative'], ['--home', '/a/../b'], ['--home','/a','--home','/b'], ['--home','/a','--json=true'], ['--home','/a','--unknown'], ['--home','/a','--timeout','Infinity'], ['--home','/a','--timeout','0'], ['--home','/a','--timeout','301'], ['--home','/a','--timeout','1e2'], ['--home','/a','--timeout']]) test(`strict arguments ${args.join(' ')}`, () => assert.throws(() => parseProbeArgs(args)));
test('bounded JSON rejects duplicate keys, malformed, deep and oversized data', () => {for (const text of ['{"x":1,"x":2}', '{', '['.repeat(30) + ']'.repeat(30), ' '.repeat(1048577)]) assert.throws(() => parseProbeJson(text));});
test('delayed reply within deadline', async t => {const f = fixture(t, {delay: 2});const r = await runProbe(f.args, f.deps);assert.equal(r.outcome, 'PASS');assert(r.timing.replyMs >= 2000);});
test('observed read without reply fails', async t => {const f = fixture(t, {reply: null, readAt: '2026-10-07T01:00:00Z'});const r = await runProbe(f.args, f.deps);assert.equal(r.outcome, 'FAIL');assert.equal(r.diagnostics.mailRead.status, 'read-unanswered');assert(r.timing.elapsedMs <= 5000);assert.equal(sends(f).length, 1);});
for (const failure of ['child-failed','child-timeout','cancelled','invalid-json']) test(`uncertain send ${failure} never repeats`, async t => {const f = fixture(t, {onCall: ({args}) => {if (args.includes('send')) {if (failure === 'invalid-json') return Buffer.from('{');throw new ProbeError(failure);}}});const r = await runProbe(f.args, f.deps);assert.equal(r.reason, 'send-outcome-unknown');assert.equal(sends(f).length, 1);});
test('full oldest-first conversation window is incomplete', async t => {const f = fixture(t, {reply:null, onCall:({args}) => args.includes('--conversation-id') ? {messages: Array.from({length:500}, () => message('request-1'))} : undefined});const r = await runProbe(f.args,f.deps);assert.equal(r.reason,'observation-incomplete');});
for (const [name, change, reason] of [
 ['global', d => d.capabilityMeta['oats.aweb'].identity.mode = 'global', 'global probe not yet implemented'],
 ['cross-deployment', d => d.workspace.deployment = '/wrong', 'cross-deployment-home'],
 ['wrong alias', d => d.capabilityMeta['oats.aweb'].alias = 'other', 'contradictory-identity'],
 ['wrong team', d => d.defaultTeam.team = 'wrong:team', 'contradictory-team'],
 ['missing root', d => delete d.providers['oats.aweb'].root, 'explicit-captured-root-required'],
 ['invalid root override', d => d.providers['oats.aweb'].roots = {'aweb:test.example': null}, 'explicit-captured-root-required'],
 ['unknown runtime', d => d.capabilityMeta['oats.aweb'].runtime = '', 'captured-runtime-unavailable']
]) test(`refuse ${name} before send`, async t => {const f=fixture(t);change(f.doc);f.save();const r=await runProbe(f.args,f.deps);assert.equal(r.reason,reason);assert.equal(sends(f).length,0);});
test('production gate has no fake release floor or live fallback',async t=>{const f=fixture(t);delete f.deps.support;const r=await runProbe(f.args,f.deps);assert.equal(r.reason,'probe-cli-and-server-support-unqualified');assert.equal(sends(f).length,0);});
test('exact candidate re-read mismatch fails', async t=>{const f=fixture(t,{onCall:({args})=>args.includes('--message-id')&&args.includes('reply-1')?{messages:[message('wrong-id')]}:undefined});const r=await runProbe(f.args,f.deps);assert.equal(r.reason,'exact-message-mismatch');});
test('target identity changed before completion fails',async t=>{let n=0;const f=fixture(t,{onCall:({args})=>{if(args.includes('whoami')&&args[1].endsWith('worker-1/.aw')&&++n===2)return {alias:'worker-1',did:ROOT_DID,custody:'self',identity_scope:'local'};}});const r=await runProbe(f.args,f.deps);assert.equal(r.reason,'identity-changed');});
test('default-team drift refused before send',async t=>{const f=fixture(t,{onCall:({args})=>args[1]==='inspect'?{schemaVersion:1,ok:true,result:{operationsApi:2,subject:{kind:'instance',home:f.home},instance:{home:f.home,harness:'codex'},layers:{messaging:{id:'oats.aweb'}},teamsSource:'live',defaultTeam:{label:'other',team:'other:team'}}}:undefined});const r=await runProbe(f.args,f.deps);assert.equal(r.reason,'default-team-changed');assert.equal(sends(f).length,0);});
test('wall-clock skew cannot extend monotonic budget',async t=>{const f=fixture(t,{reply:null});f.deps.wall=()=> '1900-01-01T00:00:00Z';const r=await runProbe(f.args,f.deps);assert(r.timing.elapsedMs<=5000);assert.equal(r.outcome,'FAIL');});
test('cancellation before dispatch performs no I/O',async t=>{const f=fixture(t);const c=new AbortController();c.abort();const r=await runProbe(f.args,{...f.deps,signal:c.signal});assert.equal(r.reason,'cancelled');assert.equal(f.calls.length,0);});
test('actual child timeout is bounded and errors are sanitized',async()=>{const budget=new ProbeBudget(.08);await assert.rejects(runProbeChild(process.execPath,['-e','console.error("secret");setInterval(()=>{},1000)'],{budget,env:process.env,cwd:process.cwd()}),e=>e.reason==='child-timeout'&&!e.message.includes('secret'));assert(budget.now()-budget.started<2000);});
test('actual child cancellation kills child',async()=>{const c=new AbortController(),budget=new ProbeBudget(3,{signal:c.signal});setTimeout(()=>c.abort(),40);await assert.rejects(runProbeChild(process.execPath,['-e','setInterval(()=>{},1000)'],{budget,env:process.env,cwd:process.cwd()}),e=>e.reason==='cancelled');});
test('decryption failure has named reason and never downgrades or provisions',async t=>{const f=fixture(t,{onCall:({args})=>{if(args.includes('--conversation-id'))throw new ProbeError('decryption-failed');}});const r=await runProbe(f.args,f.deps);assert.equal(r.reason,'decryption-failed');assert.equal(sends(f).length,1);});
test('transient read failure retries observation only',async t=>{let n=0;const f=fixture(t,{onCall:({args})=>{if(args.includes('--conversation-id')&&++n===1)throw new ProbeError('child-failed');}});const r=await runProbe(f.args,f.deps);assert.equal(r.outcome,'PASS');assert.equal(sends(f).length,1);assert.equal(n,2);});
test('root support requires both server and CLI qualification',async t=>{for(const support of [{cli:true,server:false},{cli:false,server:true},{cli:true}]){const f=fixture(t);f.deps.support=async()=>({...support,awBinary:'/fixture/aw'});const r=await runProbe(f.args,f.deps);assert.equal(r.reason,'probe-cli-and-server-support-unqualified');assert.equal(sends(f).length,0);}});
test('every subprocess phase is bounded by the total deadline',async t=>{const baseline=fixture(t);assert.equal((await runProbe(baseline.args,baseline.deps)).outcome,'PASS');for(let phase=1;phase<=baseline.calls.length;phase++){let n=0;const f=fixture(t,{onCall:({setClock})=>{if(++n===phase){setClock(5001);throw new ProbeError('child-timeout');}}});const r=await runProbe(f.args,f.deps);assert.equal(r.outcome,'FAIL',`phase ${phase}`);assert(sends(f).length<=1);assert(r.timing.elapsedMs<=5001);}});
test('cancellation at every subprocess phase stops further work',async t=>{const baseline=fixture(t);await runProbe(baseline.args,baseline.deps);for(let phase=1;phase<=baseline.calls.length;phase++){let n=0;const c=new AbortController();const f=fixture(t,{onCall:()=>{if(++n===phase){c.abort();throw new ProbeError('cancelled');}}});const r=await runProbe(f.args,{...f.deps,signal:c.signal});assert.equal(r.outcome,'FAIL',`phase ${phase}`);assert.equal(n,phase);assert(['cancelled','send-outcome-unknown'].includes(r.reason));}});
test('malformed conversation JSON cannot pass',async t=>{const f=fixture(t,{onCall:({args})=>args.includes('--conversation-id')?Buffer.from('{bad'):undefined});const r=await runProbe(f.args,f.deps);assert.equal(r.reason,'invalid-json');});
test('encrypted final exact reread must retain envelope claims',async t=>{const reply=encryptedMessage();const f=fixture(t,{reply,onCall:({args})=>{if(args.includes('--message-id')&&args.includes('reply-1')){const changed=structuredClone(reply);changed.encrypted_envelope.kind='chat';return {messages:[changed]};}}});assert.equal((await runProbe(f.args,f.deps)).reason,'reply-changed');});
test('invalid candidates never become PASS via the runner',async t=>{for(const reply of [message('reply-1',ROOT_DID),message('reply-1',TARGET_DID,TARGET_DID),message('reply-1',TARGET_DID,ROOT_DID,'wrong nonce'),{...message(),verification_status:'verified_custodial'}]){const f=fixture(t,{reply});assert.equal((await runProbe(f.args,f.deps)).outcome,'FAIL');assert.equal(sends(f).length,1);}});
test('captured settings changed during probe fail completion',async t=>{const f=fixture(t,{onCall:({args,doc,save})=>{if(args.includes('--message-id')&&args.includes('reply-1')){doc.providers['oats.aweb'].delivery='session';save();}}});assert.equal((await runProbe(f.args,f.deps)).outcome,'FAIL');});
test('symlink target home is refused',async t=>{const f=fixture(t);const alias=join(f.deployment,'alias');symlinkSync(f.home,alias);const r=await runProbe(['--home',alias],f.deps);assert.equal(r.reason,'noncanonical-home');assert.equal(sends(f).length,0);});
test('readiness and pane errors retain explicit unknowns',async t=>{const f=fixture(t,{onCall:({args})=>{if(args[1]==='readiness'||args[1]==='session')throw new ProbeError('child-timeout');}});const r=await runProbe(f.args,f.deps);assert.equal(r.outcome,'PASS');assert.equal(r.diagnostics.readiness.status,'unknown');assert.equal(r.diagnostics.pane.status,'unknown');});
test('large child output is killed without exposing content',async()=>{await assert.rejects(runProbeChild(process.execPath,['-e','process.stdout.write("secret".repeat(200000));setInterval(()=>{},1000)'],{budget:new ProbeBudget(2),env:process.env,cwd:process.cwd()}),e=>e.reason==='output-too-large');});
test('real decryption error is projected without raw stderr',async()=>{await assert.rejects(runProbeChild(process.execPath,['-e','console.error("encrypted message requires local encryption private key secret-path");process.exit(1)'],{budget:new ProbeBudget(2),env:process.env,cwd:process.cwd()}),e=>e.reason==='decryption-failed'&&!e.message.includes('secret-path'));});
test('CLI JSON/text/nonzero exit agree and emit no raw errors',async t=>{const {spawnSync}=await import('node:child_process');const f=fixture(t);const bin=new URL('../oats-package/capabilities/oats-aweb/bin/oats-aweb-probe.mjs',import.meta.url);const file=(await import('node:url')).fileURLToPath(bin);for(const json of [false,true]){const p=spawnSync(process.execPath,[file,'--home',f.home,...(json?['--json']:[])],{env:{...process.env,...f.deps.env},encoding:'utf8',timeout:5000});assert.equal(p.status,1,p.stderr);assert.equal(p.stderr,'');if(json){const r=JSON.parse(p.stdout);assert.equal(r.outcome,'FAIL');assert.equal(r.reason,'probe-cli-and-server-support-unqualified');}else assert.match(p.stdout,/^FAIL probe-cli-and-server-support-unqualified;/);assert(!p.stdout.includes('secret'));}});
test('settled metadata projection binds exact selected service origin and both floors',async()=>{const {probeMetadataUrl,projectProbeSupport}=await import('../oats-package/capabilities/oats-aweb/lib/probe-support.mjs');const policy={origins:['https://hosted.example'],cliFloor:'9.2.0',serverFloor:'8.3.0'};const facts={awebUrl:'https://hosted.example/api',cliVersion:'9.2.0',metadata:{version:'0.1.0',build:{aweb_version:'8.3.0'}},observedUrl:'https://hosted.example/meta',policy};assert.equal(probeMetadataUrl(facts.awebUrl),facts.observedUrl);assert(projectProbeSupport(facts).supported);for(const delta of [{policy:null},{observedUrl:'https://other.example/meta'},{observedUrl:'https://hosted.example/api/v1/release'},{awebUrl:'https://unrecognized.example/api'},{metadata:{version:'99.0.0'}},{metadata:{build:{aweb_version:'8.2.99'}}},{metadata:{build:{aweb_version:'garbage'}}},{metadata:{build:{aweb_version:'8.3.0-rc.1'}}},{cliVersion:'9.1.99'}])assert.equal(projectProbeSupport({...facts,...delta}).supported,false);for(const url of ['https://name:secret@hosted.example/api','https://hosted.example/api?token=secret','file:///tmp/api','https://hosted.example/other'])assert.equal(probeMetadataUrl(url),null);});
